### ISSUE TITLE
new install - error on login

### ISSUE THREAD

**Issue by encausticcello** [owncloud-docker/helm-charts#76]
Hi, I've deployed owncloud using this Helm chart to AWS EKS, and also configured an EFS ReadWriteMany persistent volume, so multiple pods can access the PV at the same time. This took some adjustments/fixes to the Helm chart, but it's running now successfully. When I try to login as the admin user though, I'm getting a 500 internal error. I enabled debug mode and got the output below. Any advice on how to fix this issue? I also have the objectstore s3 backend enabled, along with RDS mysql database. The DB connectivity looks good, and I don't see any issues the app is reporting with s3 connectivity, but I haven't been able to login to test it yet.

I should also note that I've configured an ingress - the cluster it's running on uses nginx ingress + cert manager for SSL certs. Health checks are passing and I'm able to access the UI via the ingress URL. This particular error only happens when I try to login as admin:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the [server log](https://doc.owncloud.com/server/10.13/go.php?to=admin-logfiles).


Technical details
Remote Address: 10.40.3.166
Request ID: a82b39dd233900784411777416bf99ab
Type: OCP\Files\NotFoundException
Code: 0
Message:
File: /var/www/owncloud/lib/private/Files/Node/Node.php
Line: 97

Trace
#0 /var/www/owncloud/lib/private/Files/Node/Node.php(217): OC\Files\Node\Node->getFileInfo()
#1 /var/www/owncloud/lib/private/Files/Node/Node.php(117): OC\Files\Node\Node->getPermissions()
#2 /var/www/owncloud/lib/private/Files/Node/File.php(109): OC\Files\Node\Node->checkPermissions()
#3 /var/www/owncloud/lib/private/legacy/util.php(433): OC\Files\Node\File->fopen()
#4 /var/www/owncloud/lib/private/legacy/util.php(426): OC_Util::copyr()
#5 /var/www/owncloud/lib/private/legacy/util.php(403): OC_Util::copyr()
#6 /var/www/owncloud/lib/private/User/Session.php(469): OC_Util::copySkeleton()
#7 /var/www/owncloud/lib/private/User/Session.php(1036): OC\User\Session->prepareUserLogin()
#8 /var/www/owncloud/lib/private/User/Session.php(543): OC\User\Session->loginInOwnCloud(*** sensitive parameters replaced ***)
#9 /var/www/owncloud/lib/private/User/Session.php(344): OC\User\Session->loginWithPassword(*** sensitive parameters replaced ***)
#10 /var/www/owncloud/core/Controller/LoginController.php(270): OC\User\Session->login(*** sensitive parameters replaced ***)
#11 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(169): OC\Core\Controller\LoginController->tryLogin(*** sensitive parameters replaced ***)
#12 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController()
#13 /var/www/owncloud/lib/private/AppFramework/App.php(99): OC\AppFramework\Http\Dispatcher->dispatch()
#14 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main()
#15 /var/www/owncloud/lib/private/Route/Router.php(344): OC\AppFramework\Routing\RouteActionHandler->__invoke()
#16 /var/www/owncloud/lib/kernel.php(913): OC\Route\Router->match()
#17 /var/www/owncloud/index.php(32): OC::handleRequest()
#18 {main}
```

**Comment by encausticcello** [comment]
This was due to an issue with the objectstore config. For the S3 endpoint, I just used the default value and assumed that would work. I had to add https:// to this value, and also append the bucket name. So the value that worked for S3 endpoint was actually in the format `https://s3.aws_region.amazonaws.com/bucket_name`

**Comment by xoxys** [comment]
Thanks for the update, glad you found a solution already.
